language: node_js
node_js:
  - '6'

sudo: false

cache:
  directories:
  - node_modules

script:
  - node_modules/.bin/babel-node stop.js
after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && ./upload.sh

env:
  global:
    secure: "LpGpUJXaNXYPGMSlH53a5xs4uzGPEthkk5PSkI/ev9KvfkaZEyGe/HMP92s5TQLoyUdC81L+3FMzJ29fdh8K2/hr0ZOtfg2mL2Ao5ksksAg/bPiJ0xgsdnX0KaxssqFnxGOM5p1nlam6KP1TjJBmmCGiDh+csE99EnzDhMrKD2M="
